- name: Deploy pipeline for Portfolio Web 
  hosts: localhost
  connection: local

  tasks:
    - name: Delete old repo
      ansible.builtin.shell: rm -rf ../Portfolio-Web

    - name: Clone git repo -> Portfolio-Web
      ansible.builtin.git:
        repo: git@github.com:Jazzcort/Portfolio-Web.git
        dest: ../Portfolio-Web
        key_file: ~/.ssh/tao

    - name: Copy .env
      ansible.builtin.shell: |
        cd ../Portfolio-Web && \
        cp ../env/portfolio-web.env ./.env

    - name: Build and deploy Portfolio-Web
      ansible.builtin.shell: |
        cd ../Portfolio-Web && \
        ./deploy.sh
      register: deploy_result

    - name: Display script output
      ansible.builtin.debug:
        msg: "{{ deploy_result.stdout }}"
